name: Pre-release

# Prepares a new release of the build image.
# 
# To trigger it, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header with the header with the new release's 
# version number.
#
# The workflow will automatically prepare a pull request to the `release` branch.
#

on:
  push:
    branches: [main]

jobs:

  versions:
    runs-on: ubuntu-latest
    name: Get version numbers
    outputs:
      released-version: ${{ steps.current-release.outputs.result }}
      next-version: ${{ steps.next-release.outputs.output }}
    steps:
      - uses: actions/checkout@v2
      - name: read the current release version from git tags
        id: current-release
        run: |
          git fetch --tags
          version_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          version=${version_tag/v/}
          echo "::set-output name=result::$version"
      - name: read latest version from the changelog
        id: next-release
        uses: mattwynne/changelog-action@v1.2
        with:
          args: latest
  
  create-release-pr:
    runs-on: ubuntu-latest
    name: Create / Update Release PR
    needs: versions
    if: needs.versions.outputs.released-version != needs.versions.outputs.next-version
    env:
      next_version: ${{ needs.versions.outputs.next-version }}
      released_version: ${{ needs.versions.outputs.released-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/${{ env.released_version }}
      - run: git fetch origin main
      - run: git checkout main
      - run: git checkout release/${{ env.released_version }}
      - run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git rebase -X ours main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: release/${{ env.next_version }}
          branch: pre-release/${{ env.next_version }}
          title: "Release v${{ env.next_version }}"
          body: |
            Auto-generated by the [pre-release.yaml](https://github.com/cucumber/build/blob/main/.github/workflows/pre-release.yaml) workflow, because the CHANGELOG.md
            file contains a header for v${{ env.next_version }}. 
            
            The latest git tag is v${{ env.released_version }}, so it looks like a release is needed.

            Review this PR carefully. When it's merged, the v${{ env.next_version }} release will happen automatically.
          team-reviewers: "@cucumber/build"